### ISSUE TITLE
Should this repo be open to the public?

### ISSUE THREAD

**Issue by dylansavage** [ministryofjustice/aws-root-account#251]
This seems like it should be set to private.

**Comment by jakemulley** [comment]
Hi @dylansavage 

Thanks for raising. Ministry of Justice follows the UK government's Government Design Principles which includes [Make things open, it makes things better](https://www.gov.uk/guidance/government-design-principles#make-things-open-it-makes-things-better).

UK government also has a Service Standard for digital and technology products and services within the UK government. One of the standards is to [make new source code open](https://www.gov.uk/service-manual/service-standard/point-12-make-new-source-code-open).

This repository follows the principles and standards set by wider UK government, which is why it is public. If you think you've found a security vulnerability, we have a [vulnerability disclosure policy](https://mojdigital.blog.gov.uk/vulnerability-disclosure-policy/) too that I'd encourage you to follow, where it will be picked up by our internal security team.

Hopefully that helps?

**Comment by dylansavage** [comment]
Thanks for updating @jakemulley 

Glad to know it wasn't an errant configuration and well done for keeping everything so transparent. I will close this issue.
